"""learning materials

Revision ID: 3bab220482c5
Revises: e4a14b013aa1
Create Date: 2026-10-10 16:58:45.298756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bab220482c5'
down_revision: Union[str, Sequence[str], None] = 'e4a14b013aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('text', 'url', 'file', name='materialkind', native_enum=False, length=32), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('digest', sa.Text(), nullable=True),
    sa.Column('digest_error', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=120), nullable=False),
    sa.Column('week_key', sa.Date(), nullable=True),
    sa.Column('specialization', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='materialstatus', native_enum=False, length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_learning_materials_module'), 'learning_materials', ['module'], unique=False)
    op.create_index(op.f('ix_learning_materials_week_key'), 'learning_materials', ['week_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_materials_week_key'), table_name='learning_materials')
    op.drop_index(op.f('ix_learning_materials_module'), table_name='learning_materials')
    op.drop_table('learning_materials')
    # ### end Alembic commands ###
