"""coding exercises

Revision ID: 887f56851536
Revises: 3bab220482c5
Create Date: 2026-10-10 17:07:14.263853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '887f56851536'
down_revision: Union[str, Sequence[str], None] = '3bab220482c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=False),
    sa.Column('entrypoint', sa.String(length=80), nullable=False),
    sa.Column('tests', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=120), nullable=False),
    sa.Column('week_key', sa.Date(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='exercisestatus', native_enum=False, length=32), nullable=False),
    sa.Column('reference_solution', sa.Text(), nullable=True),
    sa.Column('tests_verified', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['learning_materials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('runner', sa.Enum('browser', 'remote', name='runnerkind', native_enum=False, length=32), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('runner_error', sa.Text(), nullable=True),
    sa.Column('grading_status', sa.Enum('not_applicable', 'pending', 'done', 'failed', name='gradingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['coding_exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_attempts_exercise_id'), 'code_attempts', ['exercise_id'], unique=False)
    op.create_index('ix_code_attempts_user_created', 'code_attempts', ['user_id', 'created_at'], unique=False)
    op.create_table('code_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['coding_exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'user_id')
    )
    op.create_index(op.f('ix_code_drafts_user_id'), 'code_drafts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_drafts_user_id'), table_name='code_drafts')
    op.drop_table('code_drafts')
    op.drop_index('ix_code_attempts_user_created', table_name='code_attempts')
    op.drop_index(op.f('ix_code_attempts_exercise_id'), table_name='code_attempts')
    op.drop_table('code_attempts')
    op.drop_table('coding_exercises')
    # ### end Alembic commands ###
