"""submission ai details

Revision ID: c99307e4b630
Revises: c334b8ee73bd
Create Date: 2026-09-27 12:41:54.310787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99307e4b630'
down_revision: Union[str, Sequence[str], None] = 'c334b8ee73bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('ai_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'ai_details')
    # ### end Alembic commands ###
