"""weekly drop and quizzes

Revision ID: e4a14b013aa1
Revises: c99307e4b630
Create Date: 2026-10-10 16:48:33.039600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a14b013aa1'
down_revision: Union[str, Sequence[str], None] = 'c99307e4b630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=40), nullable=False),
    sa.Column('run_key', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job', 'run_key')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('weekly', 'interview', 'course', name='quizkind', native_enum=False, length=32), nullable=False),
    sa.Column('period_key', sa.String(length=10), nullable=False),
    sa.Column('specialization', sa.String(length=40), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=100), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('generating', 'failed', 'draft', 'published', name='quizstatus', native_enum=False, length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source_material_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('project_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_key', sa.Date(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('proposer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_key', 'proposer_id'),
    sa.UniqueConstraint('week_key', 'slot')
    )
    op.create_index(op.f('ix_project_proposals_week_key'), 'project_proposals', ['week_key'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('per_question', sa.JSON(), nullable=True),
    sa.Column('grading_status', sa.Enum('not_applicable', 'pending', 'done', 'failed', name='gradingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('grading_error', sa.Text(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id', 'user_id')
    )
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('weekly_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_key', sa.Date(), nullable=False),
    sa.Column('source_notes', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('concepts', sa.JSON(), nullable=False),
    sa.Column('summary_error', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'sent', name='briefstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_key')
    )
    op.create_table('project_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_key', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('picked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['project_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_key', 'user_id')
    )
    op.create_index(op.f('ix_project_picks_proposal_id'), 'project_picks', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_project_picks_week_key'), 'project_picks', ['week_key'], unique=False)
    op.add_column('users', sa.Column('specialization', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'specialization')
    op.drop_index(op.f('ix_project_picks_week_key'), table_name='project_picks')
    op.drop_index(op.f('ix_project_picks_proposal_id'), table_name='project_picks')
    op.drop_table('project_picks')
    op.drop_table('weekly_briefs')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_project_proposals_week_key'), table_name='project_proposals')
    op.drop_table('project_proposals')
    op.drop_table('quizzes')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
